name: medibox
description: MediBox - išmani šeimos vaistinėlė
publish_to: 'none'
version: 0.17.2+28
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  http: ^1.6.0
  camera: ^0.11.2
  google_mlkit_text_recognition: ^0.15.0
  mobile_scanner: ^7.0.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  local_auth: ^2.3.0
  timezone: ^0.10.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/medibox_family.webp
    - assets/images/medibox_family_equal.webp
    - assets/images/medibox_home_background.webp
