name: medibox
description: MediBox - išmani šeimos vaistinėlė
publish_to: 'none'
version: 0.21.4+58
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  http: ^1.6.0
  package_info_plus: ^10.2.1
  html: ^0.15.6
  image: ^4.7.0
  camera: ^0.11.2
  google_mlkit_text_recognition: ^0.15.0
  mobile_scanner: ^7.0.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  local_auth: ^2.3.0
  timezone: ^0.10.1
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  firebase_ai: ^4.0.0
  firebase_app_check: ^0.4.7
  google_sign_in: ^7.2.0
  permission_handler: ^11.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - config/google-services.json
    - config/firebase-ios.json
    - assets/images/medibox_family.webp
    - assets/images/medibox_family_equal.webp
    - assets/images/medibox_home_background.webp
    - assets/images/body_maps/adult_female.png
    - assets/images/body_maps/adult_male.png
    - assets/images/body_maps/child_female.png
    - assets/images/body_maps/child_male.png
