
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:google_mlkit_text_recognition/google_mlkit_text_recognition.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'models/models.dart'; import 'services/store.dart';
void main()=>runApp(const App());
const g=Color(0xff079b7a), mint=Color(0xffe9f8f4), navy=Color(0xff102a43);
class App extends StatelessWidget{const App({super.key});Widget build(c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'MediBox',theme:ThemeData(colorScheme:ColorScheme.fromSeed(seedColor:g),useMaterial3:true,scaffoldBackgroundColor:const Color(0xfff7faf9)),home:const Shell());}
class Shell extends StatefulWidget{const Shell({super.key});State<Shell>createState()=>_Shell();}
class _Shell extends State<Shell>{int i=0;List<Med> meds=[];bool ready=false;initState(){super.initState();Store.load().then((v)=>setState((){meds=v;ready=true;}));}void save()=>Store.save(meds);Widget build(c){if(!ready)return const Scaffold(body:Center(child:CircularProgressIndicator()));final pages=[Home(meds:meds,onChanged:(){save();setState((){});}),Cabinet(meds:meds,onChanged:(){save();setState((){});}),Symptoms(meds:meds),const Family(),const Reminders()];return Scaffold(body:SafeArea(child:pages[i]),bottomNavigationBar:NavigationBar(selectedIndex:i,onDestinationSelected:(v)=>setState(()=>i=v),destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),label:'Pagrindinis'),NavigationDestination(icon:Icon(Icons.medication_outlined),label:'Vaistinėlė'),NavigationDestination(icon:Icon(Icons.health_and_safety_outlined),label:'Man bloga'),NavigationDestination(icon:Icon(Icons.people_outline),label:'Šeima'),NavigationDestination(icon:Icon(Icons.notifications_outlined),label:'Priminimai')]));}}
Widget box(Widget x)=>Card(elevation:0,color:Colors.white,child:Padding(padding:const EdgeInsets.all(16),child:x));
class Home extends StatelessWidget{final List<Med>meds;final VoidCallback onChanged;const Home({super.key,required this.meds,required this.onChanged});Widget build(c)=>ListView(padding:const EdgeInsets.all(18),children:[const Row(children:[CircleAvatar(backgroundColor:g,child:Icon(Icons.add,color:Colors.white)),SizedBox(width:10),Text('MediBox',style:TextStyle(fontSize:29,fontWeight:FontWeight.bold,color:navy))]),const SizedBox(height:20),const Text('Labas! 👋',style:TextStyle(fontSize:26,fontWeight:FontWeight.bold)),const Text('Tavo vaistinėlė šiandien.'),const SizedBox(height:14),box(const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Šiandien',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),ListTile(leading:Icon(Icons.check_circle,color:g),title:Text('Euthyrox 50 µg'),subtitle:Text('07:00 • Išgerta')),ListTile(leading:Icon(Icons.schedule),title:Text('Loratadine 10 mg'),subtitle:Text('14:00 • Laukia')),ListTile(leading:Icon(Icons.schedule),title:Text('Magnis'),subtitle:Text('21:00 • Laukia'))])),const SizedBox(height:10),FilledButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Scan(meds:meds,onChanged:onChanged))),icon:const Icon(Icons.camera_alt),label:const Padding(padding:EdgeInsets.all(15),child:Text('Nuskenuoti vaistą / čekį'))),const SizedBox(height:8),FilledButton.tonalIcon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Symptoms(meds:meds))),icon:const Icon(Icons.health_and_safety),label:const Padding(padding:EdgeInsets.all(15),child:Text('Man bloga'))),const SizedBox(height:10),box(Column(children:[ListTile(leading:const Icon(Icons.inventory_2,color:Colors.orange),title:Text('${meds.where((x)=>x.stock<10).length} preparatų atsargos mažos')),ListTile(leading:const Icon(Icons.event,color:Colors.red),title:Text('${meds.length} preparatai stebimi pagal galiojimą'))]))]);}
class Cabinet extends StatelessWidget{final List<Med>meds;final VoidCallback onChanged;const Cabinet({super.key,required this.meds,required this.onChanged});Widget build(c)=>ListView(padding:const EdgeInsets.all(18),children:[const Text('Mano vaistinėlė',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:10),...meds.map((m)=>Card(child:ListTile(leading:const CircleAvatar(backgroundColor:mint,child:Icon(Icons.medication,color:g)),title:Text('${m.name} ${m.strength}',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${m.substance}\n${m.category} • liko ${m.stock} • ${m.expiry}'),isThreeLine:true,onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>MedPage(m:m,onChanged:onChanged))))),OutlinedButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ManualAdd(meds:meds,onChanged:onChanged))),icon:const Icon(Icons.add),label:const Text('Pridėti rankiniu būdu'))]);}
class MedPage extends StatefulWidget{final Med m;final VoidCallback onChanged;const MedPage({super.key,required this.m,required this.onChanged});State<MedPage>createState()=>_MedPage();}
class _MedPage extends State<MedPage>{Widget build(c){final m=widget.m;return Scaffold(appBar:AppBar(title:Text(m.name)),body:ListView(padding:const EdgeInsets.all(18),children:[box(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${m.name} ${m.strength}',style:const TextStyle(fontSize:25,fontWeight:FontWeight.bold)),Text('Veiklioji medžiaga: ${m.substance}'),Chip(label:Text(m.prescription?'Receptinis':'Nereceptinis')),const Divider(),const Text('Kam vartojamas?',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),Text(m.purpose)])),box(const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Svarbu',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),Text('Vadovaukitės konkretaus preparato pakuotės lapeliu. MediBox nekeičia gydytojo paskirto gydymo ir savarankiškai neskiria receptinių vaistų.')])),box(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Likutis: ${m.stock} vnt.',style:const TextStyle(fontWeight:FontWeight.bold)),Text('Galioja iki ${m.expiry}'),Row(children:[IconButton(onPressed:m.stock>0?(){setState(()=>m.stock--);widget.onChanged();}:null,icon:const Icon(Icons.remove_circle_outline)),const Text('Pažymėti vieną panaudotą')])]))]));}}
class ManualAdd extends StatefulWidget{final List<Med>meds;final VoidCallback onChanged;const ManualAdd({super.key,required this.meds,required this.onChanged});State<ManualAdd>createState()=>_ManualAdd();}
class _ManualAdd extends State<ManualAdd>{final n=TextEditingController(),s=TextEditingController(),st=TextEditingController(),ex=TextEditingController();Widget build(c)=>Scaffold(appBar:AppBar(title:const Text('Pridėti vaistą')),body:ListView(padding:const EdgeInsets.all(18),children:[for(final x in [('Pavadinimas',n),('Veiklioji medžiaga',s),('Stiprumas',st),('Galioja iki YYYY-MM',ex)])Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:x.$2,decoration:InputDecoration(labelText:x.$1,border:const OutlineInputBorder()))),FilledButton(onPressed:(){if(n.text.isEmpty)return;widget.meds.add(Med(id:DateTime.now().millisecondsSinceEpoch.toString(),name:n.text,substance:s.text,strength:st.text,purpose:'Informaciją patikrinkite pakuotės lapelyje.',category:'Kita',expiry:ex.text,stock:1));widget.onChanged();Navigator.pop(c);},child:const Text('Išsaugoti'))]));}}
class Scan extends StatefulWidget{final List<Med>meds;final VoidCallback onChanged;const Scan({super.key,required this.meds,required this.onChanged});State<Scan>createState()=>_Scan();}
class _Scan extends State<Scan>{String text='';bool busy=false;Future<void>ocr(ImageSource src)async{final f=await ImagePicker().pickImage(source:src,imageQuality:90);if(f==null)return;setState(()=>busy=true);final r=TextRecognizer(script:TextRecognitionScript.latin);final out=await r.processImage(InputImage.fromFilePath(f.path));await r.close();setState((){text=out.text;busy=false;});}Widget build(c)=>Scaffold(appBar:AppBar(title:const Text('Skenuoti')),body:ListView(padding:const EdgeInsets.all(18),children:[const Text('Vaisto dėžutė, galiojimas arba čekis',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:12),FilledButton.icon(onPressed:busy?null:()=>ocr(ImageSource.camera),icon:const Icon(Icons.camera_alt),label:const Text('Fotografuoti')),OutlinedButton.icon(onPressed:busy?null:()=>ocr(ImageSource.gallery),icon:const Icon(Icons.photo_library),label:const Text('Pasirinkti nuotrauką')),OutlinedButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const BarcodePage())),icon:const Icon(Icons.qr_code_scanner),label:const Text('Skenuoti brūkšninį / QR kodą')),if(busy)const Padding(padding:EdgeInsets.all(20),child:Center(child:CircularProgressIndicator())),if(text.isNotEmpty)box(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('OCR atpažintas tekstas',style:TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:8),SelectableText(text),const SizedBox(height:10),const Text('Prieš išsaugant vaistą patvirtinkite atpažintą pavadinimą ir stiprumą.',style:TextStyle(color:Colors.orange))]))]));}}
class BarcodePage extends StatelessWidget{const BarcodePage({super.key});Widget build(c)=>Scaffold(appBar:AppBar(title:const Text('Kodo skenavimas')),body:MobileScanner(onDetect:(x){final v=x.barcodes.firstOrNull?.rawValue;if(v!=null){Navigator.pop(c);ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('Atpažintas kodas: $v')));}}));}
class Symptoms extends StatelessWidget{final List<Med>meds;const Symptoms({super.key,required this.meds});Widget build(c)=>Scaffold(appBar:AppBar(title:const Text('Man bloga')),body:ListView(padding:const EdgeInsets.all(18),children:[const Text('Kas labiausiai vargina?',style:TextStyle(fontSize:25,fontWeight:FontWeight.bold)),const Text('Vedlys ne diagnozuoja – pirmiausia tikrina pavojingus požymius.'),...['Skausmas','Karščiavimas','Peršalimas','Pilvo problemos','Alergija','Viduriavimas','Vidurių užkietėjimas','Odos problemos'].map((x)=>Card(child:ListTile(title:Text(x),leading:const Icon(Icons.health_and_safety,color:g),trailing:const Icon(Icons.chevron_right),onTap:x=='Pilvo problemos'?()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Triage(meds:meds))):()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Matches(meds:meds,category:x=='Alergija'?'Alergija':x=='Skausmas'?'Skausmas':'Kita')))))]));}}
class Triage extends StatefulWidget{final List<Med>meds;const Triage({super.key,required this.meds});State<Triage>createState()=>_Triage();}
class _Triage extends State<Triage>{bool severe=false,blood=false,vomit=false,fever=false;Widget build(c)=>Scaffold(appBar:AppBar(title:const Text('Pilvo problemos')),body:ListView(padding:const EdgeInsets.all(18),children:[const Text('Saugumo patikra',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const Text('Pažymėkite, jei tinka:'),SwitchListTile(value:severe,onChanged:(v)=>setState(()=>severe=v),title:const Text('Labai stiprus ar staigus skausmas')),SwitchListTile(value:blood,onChanged:(v)=>setState(()=>blood=v),title:const Text('Kraujas vemiant ar tuštinantis')),SwitchListTile(value:vomit,onChanged:(v)=>setState(()=>vomit=v),title:const Text('Nuolatinis vėmimas / negalite išlaikyti skysčių')),SwitchListTile(value:fever,onChanged:(v)=>setState(()=>fever=v),title:const Text('Karščiavimas kartu su stiprėjančiu pilvo skausmu')),FilledButton(onPressed:(){final d=severe||blood||vomit||fever;Navigator.push(c,MaterialPageRoute(builder:(_)=>d?const Danger():Matches(meds:widget.meds,category:'Virškinimas')));},child:const Text('Tęsti'))]));}}
class Danger extends StatelessWidget{const Danger({super.key});Widget build(c)=>Scaffold(appBar:AppBar(title:const Text('Svarbu')),body:Padding(padding:const EdgeInsets.all(22),child:box(const Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.warning_rounded,size:72,color:Colors.red),Text('Vaisto parinkimas sustabdytas',style:TextStyle(fontSize:23,fontWeight:FontWeight.bold)),SizedBox(height:10),Text('Pagal pažymėtus simptomus reikalingas medicininis įvertinimas. Jei būklė sunki, staigi ar greitai blogėja, kreipkitės skubios pagalbos.',textAlign:TextAlign.center)]))));}
class Matches extends StatelessWidget{final List<Med>meds;final String category;const Matches({super.key,required this.meds,required this.category});Widget build(c){final m=meds.where((x)=>x.category==category&&!x.prescription).toList();return Scaffold(appBar:AppBar(title:const Text('Ką turiu vaistinėlėje?')),body:ListView(padding:const EdgeInsets.all(18),children:[const Text('Pagal jūsų pasirinktą simptomų kategoriją',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const Text('Rodomi tik jūsų vaistinėlėje esantys nereceptiniai preparatai. Tai nėra individualus gydymo paskyrimas.'),const SizedBox(height:12),if(m.isEmpty)box(const Text('Šiai kategorijai tinkamai pažymėtų nereceptinių preparatų jūsų vaistinėlėje nerasta.')),...m.map((x)=>Card(child:ListTile(title:Text('${x.name} ${x.strength}'),subtitle:Text('${x.purpose}\nLiko ${x.stock}'),isThreeLine:true,onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>MedPage(m:x,onChanged:(){}))))))]));}}
class Family extends StatelessWidget{const Family({super.key});Widget build(c)=>ListView(padding:const EdgeInsets.all(18),children:[const Text('Mano šeima',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),...['Aš','Vaikas','Mama'].map((x)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(x),subtitle:const Text('Atskiras vaistų ir priminimų profilis'),trailing:const Icon(Icons.chevron_right)))),FilledButton.tonalIcon(onPressed:(){},icon:const Icon(Icons.person_add),label:const Text('Pridėti šeimos narį'))]);}
class Reminders extends StatelessWidget{const Reminders({super.key});Widget build(c)=>ListView(padding:const EdgeInsets.all(18),children:[const Text('Priminimai',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),box(const Column(children:[ListTile(leading:Icon(Icons.check_circle,color:g),title:Text('07:00 • Euthyrox 50 µg'),subtitle:Text('Išgerta')),ListTile(leading:Icon(Icons.schedule),title:Text('14:00 • Loratadine 10 mg'),subtitle:Text('Laukia')),ListTile(leading:Icon(Icons.schedule),title:Text('21:00 • Magnis'),subtitle:Text('Laukia'))])),FilledButton.icon(onPressed:(){},icon:const Icon(Icons.add_alarm),label:const Text('Pridėti priminimą'))]);}
